//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Discapacidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_Discapacidad()
        {
            this.Discapacidad = new HashSet<Discapacidad>();
        }
    
        public byte tidi_id { get; set; }
        public string tidi_descripcion { get; set; }
        public string tidi_estatus { get; set; }
        public System.DateTime tidi_add { get; set; }
        public Nullable<System.DateTime> tidi_update { get; set; }
        public Nullable<System.DateTime> tidi_delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discapacidad> Discapacidad { get; set; }
    }
}
